# key bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Sensible
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 5
# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 10000
# Increase tmux messages display duration from 750ms to 4s
set -g display-time 2000
# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 10
# vi keys, even for vim users
set -g status-keys vi
# Focus events enabled for terminals that support them
set -g focus-events on
# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on


# other
set -s exit-empty off
set -s exit-unattached off
set -ga terminal-overrides ",xterm-256color:Tc" 
set -gw automatic-rename off
set -g status-style 'fg=#F7768E'
set -g mouse off


